
Strict

Import "newton-dynamics/coreLibrary_300/source/core/*.h"
Import "newton-dynamics/coreLibrary_300/source/physics/*.h"
Import "newton-dynamics/coreLibrary_300/source/meshUtil/*.h"
Import "newton-dynamics/coreLibrary_300/source/pthreads.2/*.h"

?Win32
' pthread library
Import "newton-dynamics/coreLibrary_300/source/pthreads.2/pthread.c"
?

' dg low level library
Import "newton-dynamics/coreLibrary_300/source/core/dgAABBPolygonSoup.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgAsyncThread.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgConvexHull3d.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgConvexHull4d.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dg.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgCRC.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgDebug.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgDelaunayTetrahedralization.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgGeneralMatrix.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgGeneralVector.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgGoogol.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgIntersections.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgMatrix.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgMemory.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgMutexThread.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgNode.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgPolygonSoupBuilder.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgPolyhedra.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgPolyhedraMassProperties.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgQuaternion.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgRandom.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgRefCounter.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgRef.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgSmallDeterminant.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgSPDMatrix.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgObb.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgThread.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgThreadHive.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgTree.cpp"
Import "newton-dynamics/coreLibrary_300/source/core/dgTypes.cpp"

' Physics engine files
Import "newton-dynamics/coreLibrary_300/source/physics/dgBody.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgDynamicBody.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgKinematicBody.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgBallConstraint.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgBilateralConstraint.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgBody.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgDynamicBody.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgKinematicBody.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgBodyMasterList.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgBroadPhase.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgBroadPhaseDefault.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgBroadPhasePersistent.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionBox.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionBVH.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionCapsule.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionChamferCylinder.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionCompoundFractured.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionCompound.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionCone.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionConvex.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionConvexHull.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionConvexPolygon.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollision.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionCylinder.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionDeformableClothPatch.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionDeformableSolidMesh.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionDeformableMesh.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionHeightField.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionInstance.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionMesh.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionNull.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionScene.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionSphere.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionTaperedCapsule.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionTaperedCylinder.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCollisionUserMesh.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgConstraint.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgContact.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgCorkscrewConstraint.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgDeformableBody.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgDeformableContact.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgHingeConstraint.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgNarrowPhaseCollision.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgSlidingConstraint.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgUniversalConstraint.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgUpVectorConstraint.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgUserConstraint.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgWorld.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgDeformableBodiesUpdate.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgWorldDynamicsParallelSolver.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgWorldDynamicsSimpleSolver.cpp"
Import "newton-dynamics/coreLibrary_300/source/physics/dgWorldDynamicUpdate.cpp"

Import "newton-dynamics/coreLibrary_300/source/meshUtil/dgMeshEffect1.cpp"
Import "newton-dynamics/coreLibrary_300/source/meshUtil/dgMeshEffect2.cpp"
Import "newton-dynamics/coreLibrary_300/source/meshUtil/dgMeshEffect3.cpp"
Import "newton-dynamics/coreLibrary_300/source/meshUtil/dgMeshEffect4.cpp"
Import "newton-dynamics/coreLibrary_300/source/meshUtil/dgMeshEffect5.cpp"
Import "newton-dynamics/coreLibrary_300/source/meshUtil/dgMeshEffect6.cpp"

Import "newton-dynamics/coreLibrary_300/source/newton/Newton.cpp"
Import "newton-dynamics/coreLibrary_300/source/newton/NewtonClass.cpp"
