
Strict

Import "source/core/*.h"

Import "source/core/dg.cpp"
Import "source/core/dgRef.cpp"
Import "source/core/dgCRC.cpp"
Import "source/core/dgTree.cpp"
Import "source/core/dgNode.cpp"
Import "source/core/dgTypes.cpp"
Import "source/core/dgMatrix.cpp"
Import "source/core/dgGoogol.cpp"
Import "source/core/dgMemory.cpp"
Import "source/core/dgSphere.cpp"
Import "source/core/dgRandom.cpp"
Import "source/core/dgThreads.cpp"
Import "source/core/dgPolyhedra.cpp"
Import "source/core/dgQuaternion.cpp"
Import "source/core/dgConvexHull3d.cpp"
Import "source/core/dgConvexHull4d.cpp"
Import "source/core/dgIntersections.cpp"
Import "source/core/dgAABBPolygonSoup.cpp"
Import "source/core/dgSmallDeterminant.cpp"
Import "source/core/dgPolygonSoupBuilder.cpp"
Import "source/core/dgPolyhedraMassProperties.cpp"
Import "source/core/dgDelaunayTetrahedralization.cpp"

Import "source/physics/*.h"

Import "source/physics/dgWorld.cpp"
Import "source/physics/dgBody.cpp"
Import "source/physics/dgMeshEffect.cpp"
Import "source/physics/dgMeshEffect2.cpp"
Import "source/physics/dgMeshEffectSolidTree.cpp"
Import "source/physics/dgCollisionConvex.cpp"
Import "source/physics/dgBallConstraint.cpp"
Import "source/physics/dgBilateralConstraint.cpp"
Import "source/physics/dgCorkscrewConstraint.cpp"
Import "source/physics/dgHingeConstraint.cpp"
Import "source/physics/dgNarrowPhaseCollision.cpp"
Import "source/physics/dgBroadPhaseCollision.cpp"
Import "source/physics/dgMinkowskiConv.cpp"
Import "source/physics/dgCollisionBox.cpp"
Import "source/physics/dgCollisionCapsule.cpp"
Import "source/physics/dgCollisionBVH.cpp"
Import "source/physics/dgCollisionMesh.cpp"
Import "source/physics/dgCollisionUserMesh.cpp"
Import "source/physics/dgCollisionChamferCylinder.cpp"
Import "source/physics/dgPointToCurveConstraint.cpp"
Import "source/physics/dgCollisionCone.cpp"
Import "source/physics/dgCollisionConvexHull.cpp"
Import "source/physics/dgSlidingConstraint.cpp"
Import "source/physics/dgCollisionConvexModifier.cpp"
Import "source/physics/dgUniversalConstraint.cpp"
Import "source/physics/dgCollision.cpp"
Import "source/physics/dgUpVectorConstraint.cpp"
Import "source/physics/dgCollisionCylinder.cpp"
Import "source/physics/dgUserConstraint.cpp"
Import "source/physics/dgCollisionEllipse.cpp"
Import "source/physics/dgCollisionNull.cpp"
Import "source/physics/dgCollisionScene.cpp"
Import "source/physics/dgCollisionCompoundBreakable.cpp"
Import "source/physics/dgCollisionHeightField.cpp"
Import "source/physics/dgWorldDynamicUpdate.cpp"
Import "source/physics/dgCollisionSphere.cpp"
Import "source/physics/dgCollisionCompound.cpp"
Import "source/physics/dgConnectorConstraint.cpp"
Import "source/physics/dgConstraint.cpp"
Import "source/physics/dgBodyMasterList.cpp"
Import "source/physics/dgContact.cpp"

Import "source/newton/Newton.cpp"
Import "source/newton/NewtonClass.cpp"

